import { SafeHydrate } from '@/core/config/Hooks'
import { ClientComponent } from '@/core/Auth/QueryClientConfig'

// Styles
import './styles.css'
import './normalize.css'

export const metadata = {
  title: 'A Netflix clon',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <SafeHydrate>
          <ClientComponent>
            {children}
          </ClientComponent>
        </SafeHydrate>
      </body>
    </html>
  )
}
